name: Update readme

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install

    - name: Generate readme
      env:
       WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}    
      run: node build-svg.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Jin Hyung Park
        author_email: hophfg@yahoo.co.kr
        message: "Auto updating my readme"
        add: "*.svg"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate Snakes
      uses: Platane/snk@master
      id: snake-gif
      with:
          github_user_name: jypthemiracle
          # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        
      # show the status of the build. Makes it easier for debugging (if there's any issues).
    - run: git status

      # Push the changes
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true

    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        # the output branch we mentioned above
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
